#!/usr/bin/env bash
# Installs and sets up a simple Nginx web server on web-01

apt-get update
apt-get install nginx -y

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
printf %s "server {
	listen    80 default_server;
	listen    [::]:80 default_server;
	root      /etc/nginx/html;
	index     index.html index.htm;
}
" > /etc/nginx/sites-available/default

service nginx restart
