#!/usr/bin/env bash
# Install and config a simple Nginx web server on web-01
ROOT_FILE_PATH="/var/www/html/index.html"
SERVER_BLOCK_PATH="/etc/nginx/sites-available/default"

TO_APPEND="\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4\$request_uri;\n\t}"

sudo apt-get update
sudo apt-get -y install nginx

sudo touch "$ROOT_FILE_PATH"
sudo chmod a+w "$ROOT_FILE_PATH"
echo "Hello World!" > "$ROOT_FILE_PATH"
sudo chmod a-w "$ROOT_FILE_PATH"

# Inserting changes into the folder
sudo sed -i "46 a\ $TO_APPEND" "$SERVER_BLOCK_PATH"

# Restart server
sudo service nginx restart
