#!/usr/bin/env bash
# configures an Ubuntu server as given below.
#    -  localhost resolves to 127.0.0.2
#    - facebook.com resolves to 8.8.8.8

echo "127.0.0.2		localhost" > /etc/hosts
echo "8.8.8.8		facebook.com" >> /etc/hosts
