#!/usr/bin/env bash
# configures an Ubuntu server as given below.
#    -  localhost resolves to 127.0.0.2
#    - facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts2
echo "127.0.0.2		localhost" > ~/hosts2
echo "8.8.8.8		facebook.com" >> ~/hosts2
cp ~/hosts2 /etc/hosts
